<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <PackageId>GMap.NET.WinForms</PackageId>
    <Product>GMap.NET.WindowsForms</Product>
    <AssemblyTitle>GMap.NET.WindowsForms</AssemblyTitle>
    
    <TargetFrameworks>net481;netcoreapp3.1;net10.0-windows</TargetFrameworks>
    <UseWindowsForms>true</UseWindowsForms>
    <DefineConstants>ContinuesMapNo;$(DefineConstants)</DefineConstants>
    
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net481'">
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
  </PropertyGroup>

	<PropertyGroup>
		<NoWarn>$(NoWarn);WFO1000</NoWarn>
	</PropertyGroup>

    <PropertyGroup Condition="$([System.Text.RegularExpressions.Regex]::IsMatch('$(TargetFramework)', '^net\d'))">
        <DefineConstants>NETFRAMEWORK;ContinuesMapNo;$(DefineConstants)</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition="$([System.Text.RegularExpressions.Regex]::IsMatch('$(TargetFramework)', '^netstandard\d'))">
        <DefineConstants>NETSTANDARD;ContinuesMapNo;$(DefineConstants)</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition="$([System.Text.RegularExpressions.Regex]::IsMatch('$(TargetFramework)', '^netcoreapp\d'))">
        <DefineConstants>NETCORE;ContinuesMapNo;$(DefineConstants)</DefineConstants>
    </PropertyGroup>
    <ItemGroup>
      <PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
    </ItemGroup>
    
  <ItemGroup>
    <ProjectReference Include="..\GMap.NET.Core\GMap.NET.Core.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net481'">
    <PackageReference Include="System.Resources.Extensions">
      <Version>10.0.1</Version>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
