<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <PlatformTarget>x64</PlatformTarget>
    
     <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <ApplicationUseWaitCursor>true</ApplicationUseWaitCursor>
    <ApplicationVisualStyles>true</ApplicationVisualStyles>
    <ApplicationDefaultFont>Microsoft Sans Serif, 8.25pt</ApplicationDefaultFont>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Data - Копировать\**" />
    <EmbeddedResource Remove="Data - Копировать\**" />
    <None Remove="Data - Копировать\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Data\calibration.json" />
    <None Remove="Maps\MapTest.svg" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Data\calibration.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Maps\MapTest.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Accord.Math" Version="3.8.0" />
    <PackageReference Include="CoordinateSharp" Version="3.3.2.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="ProjNet" Version="2.1.0" />
    <PackageReference Include="SharpDX" Version="4.2.0" />
    <PackageReference Include="SharpDX.Direct2D1" Version="4.2.0" />
    <PackageReference Include="SharpDX.DXGI" Version="4.2.0" />
    <PackageReference Include="Svg" Version="3.4.7" />
    <PackageReference Include="System.IO.Ports" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GMap.NET\GMap.NET.Core\GMap.NET.Core.csproj" />
    <ProjectReference Include="..\GMap.NET\GMap.NET.WindowsForms\GMap.NET.WindowsForms.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="settings\scale.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>